services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.3.2
        hostname: zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: confluentinc/cp-kafka:7.3.2
        hostname: kafka
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_NUM_PARTITIONS: 3
            KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 3
            KAFKA_DEFAULT_REPLICATION_FACTOR: 1
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_MIN_INSYNC_REPLICAS: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    conduktor-platform:
        image: conduktor/conduktor-platform:1.15.0
        ports:
            - 8080:8080
        depends_on:
            - kafka
        environment:
            CDK_ORGANIZATION_NAME: "default"
            CDK_ADMIN_EMAIL: "admin@conduktor.io"
            CDK_ADMIN_PASSWORD: "admin"
            CDK_CLUSTERS_0_ID: "Local"
            CDK_CLUSTERS_0_NAME: "Local Cluster"
            CDK_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
