spring:
    application:
        name: kafka-demo

server:
    port: 9001

kafka:
    bootstrap-servers: localhost:9092
    producer:
        compressionType: none
        batchSize: 64000
        lingerMs: 10
        acks: all
        async: true
    consumer:
        maxPollIntervalMs: 30000
        maxPollRecords: 500
    outboundTopic: "demo-topic"
